name: bowtie-vs-pave
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - bowtie2
  - samtools
  - bcftools
  - multiqc
  - docopt
  - loguru
  - pandas
  - seaborn
  - matplotlib
